name: look_to_the_cook
description: A kitchen inventory tracking and alert application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # make icons with links (i.e. GitHub, email, LinkedIn)
  font_awesome_flutter: any
  # launch URL in browser
  url_launcher: ^5.4.1
  # adds ios icon capabilities to application
  cupertino_icons: ^0.1.2
  # allow the app to check for mobile data, or wifi connectivity
  connectivity: ^0.4.6+2
  # for AWS Cognito authentication
  amazon_cognito_identity_dart: ^0.0.22
  # for secure iOS keychain storage and Android local storage
  flutter_secure_storage: ^3.3.1+1
  # for popup alerts throughout screens
  rflutter_alert: ^1.0.3
  # used for designing loading spinners
  flutter_spinkit: ^4.1.2
  # used to signal open and close of loading spinners
  modal_progress_hud: ^0.1.3
  # used for progress bar indicator
  http: ^0.12.0
  # used to scale text on multiple screens
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
